# Generated by Django 4.2.3 on 2023-07-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
