# Generated by Django 4.2.3 on 2023-07-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_attack_formone_label_user_delete_connection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_name', models.CharField(max_length=20)),
                ('attack_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='attack',
            name='attack_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.attacks'),
        ),
    ]
