# Generated by Django 4.2.3 on 2023-08-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_message_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
