# Generated by Django 4.2.3 on 2023-08-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
