# Generated by Django 4.2.3 on 2023-08-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_formone_user_remove_message_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
