# Generated by Django 4.2.3 on 2023-08-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_label_remove_message_user_message_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formone',
            old_name='label',
            new_name='label_name',
        ),
    ]
