# Generated by Django 4.2.3 on 2023-08-29 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_label_name_formone_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formone',
            name='label',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='base.label'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formone',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(help_text='Give this connection a name to identify it e.g Connection_01', max_length=255, unique=True),
        ),
    ]
