# Generated by Django 4.2.3 on 2023-08-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_formone_label_alter_formone_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formone',
            name='is_DOS',
            field=models.IntegerField(choices=[(0, 'Not a DOS attack'), (1, 'DOS attack')], default=0),
            preserve_default=False,
        ),
    ]
