# Generated by Django 4.2.3 on 2023-08-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_formone_is_dos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formone',
            name='is_DOS',
            field=models.IntegerField(choices=[(0, 'Not a DOS attack'), (1, 'DOS attack')], null=True),
        ),
    ]
