# Generated by Django 4.2.3 on 2023-08-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_formone_is_dos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formone',
            old_name='label',
            new_name='label_name',
        ),
    ]
