# Generated by Django 4.2.3 on 2023-08-31 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_label_name_formone_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formone',
            name='label',
            field=models.CharField(help_text='Give this connection a name to identify it e.g Connection_01', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='attack_name',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='base.attack'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='label',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='base.formone'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
